#!/usr/bin/env python3
"""
3D Perler bead disassembly: panel pattern and slot generator.

Takes a structured disassembly plan JSON (generated by Claude's vision analysis)
and produces flat bead pattern PNGs for each panel with interlocking slot designs.
"""

import argparse
import json
import sys
from pathlib import Path
from typing import List, Tuple

import numpy as np
from PIL import Image, ImageDraw, ImageFont

sys.path.insert(0, str(Path(__file__).parent))
from color_science import load_palette, filter_palette, rgb_to_lab, match_colors
from grid_render import render_pattern, get_font


# --- Color Map to Grid ---

# Map common color names to approximate RGB
COLOR_NAME_MAP = {
    "white": [255, 255, 255], "black": [0, 0, 0],
    "red": [220, 30, 30], "green": [30, 180, 30], "blue": [30, 30, 220],
    "yellow": [255, 220, 0], "orange": [255, 140, 0], "purple": [130, 30, 180],
    "pink": [255, 150, 180], "brown": [140, 80, 30], "gray": [150, 150, 150],
    "grey": [150, 150, 150], "cyan": [0, 200, 220], "beige": [230, 210, 180],
    "tan": [200, 170, 130], "cream": [255, 250, 220], "gold": [255, 200, 50],
    "skin": [240, 200, 160], "dark red": [150, 20, 20], "dark blue": [20, 20, 150],
    "dark green": [20, 100, 20], "light blue": [100, 180, 255],
    "light green": [100, 255, 100], "light yellow": [255, 255, 150],
}


def color_hint_to_rgb(hint: str) -> list:
    """Convert a color hint string to approximate RGB."""
    hint_lower = hint.lower().strip()

    # Try hex
    if hint_lower.startswith("#") and len(hint_lower) in (4, 7):
        h = hint_lower[1:]
        if len(h) == 3:
            h = h[0]*2 + h[1]*2 + h[2]*2
        return [int(h[i:i+2], 16) for i in (0, 2, 4)]

    # Try named color
    if hint_lower in COLOR_NAME_MAP:
        return COLOR_NAME_MAP[hint_lower]

    # Default to gray
    return [180, 180, 180]


def generate_panel_grid(panel: dict, palette: dict) -> np.ndarray:
    """Generate a bead grid for a panel from its color_map regions.

    Returns: (height, width) int array of palette indices.
    """
    w = panel["width"]
    h = panel["height"]

    # Create RGB image from color regions
    rgb_image = np.full((h, w, 3), 200, dtype=np.uint8)  # default gray

    if "color_map" in panel and "regions" in panel["color_map"]:
        for region in panel["color_map"]["regions"]:
            rx, ry = region.get("x", 0), region.get("y", 0)
            rw, rh = region.get("w", w), region.get("h", h)
            color = color_hint_to_rgb(region.get("color_hint", "gray"))
            # Clamp to bounds
            x1 = max(0, min(rx, w))
            y1 = max(0, min(ry, h))
            x2 = max(0, min(rx + rw, w))
            y2 = max(0, min(ry + rh, h))
            rgb_image[y1:y2, x1:x2] = color

    # Match to palette
    flat = rgb_image.reshape(-1, 3)
    flat_lab = rgb_to_lab(flat)
    indices = match_colors(flat_lab, palette)
    return indices.reshape(h, w)


# --- Slot Design ---

def design_slots(
    panel: dict,
    all_panels: dict,
    slot_width: int = 1,
    slot_depth_ratio: float = 0.4,
    min_spacing: int = 3,
) -> list:
    """Design interlocking slots for panel connections.

    Returns: list of slot dicts with position, size, and direction.
    """
    slots = []
    panel_w = panel["width"]
    panel_h = panel["height"]
    connects = panel.get("connects_to", [])

    for conn_id in connects:
        if conn_id not in all_panels:
            continue
        other = all_panels[conn_id]

        # Determine which edge connects
        # Simple heuristic: if panels share a dimension, they connect on that edge
        # For now, distribute slots along the longest shared edge
        shared_len = min(panel_h, other.get("height", panel_h))
        slot_depth = max(1, min(int(shared_len * slot_depth_ratio), shared_len // 2))
        num_slots = max(1, shared_len // (slot_depth + min_spacing))

        # Determine edge (right edge for simplicity — Claude can specify in plan)
        edge = panel.get("slot_edge", {}).get(conn_id, "right")

        spacing = shared_len / (num_slots + 1)
        for i in range(num_slots):
            pos = int(spacing * (i + 1))
            slot = {
                "connects_to": conn_id,
                "edge": edge,
                "position": pos,  # along the edge
                "width": slot_width,
                "depth": slot_depth,
            }
            slots.append(slot)

    return slots


def apply_slots_to_grid(grid: np.ndarray, slots: list) -> np.ndarray:
    """Mark slot positions on the grid with -2 (slot marker).

    Returns: modified grid (copy).
    """
    result = grid.copy()
    h, w = result.shape

    for slot in slots:
        edge = slot["edge"]
        pos = slot["position"]
        depth = slot["depth"]
        sw = slot["width"]

        if edge == "right":
            for dy in range(-sw//2, sw//2 + 1):
                y = pos + dy
                if 0 <= y < h:
                    for dx in range(depth):
                        x = w - 1 - dx
                        if 0 <= x < w:
                            result[y, x] = -2
        elif edge == "left":
            for dy in range(-sw//2, sw//2 + 1):
                y = pos + dy
                if 0 <= y < h:
                    for dx in range(depth):
                        if 0 <= dx < w:
                            result[y, dx] = -2
        elif edge == "top":
            for dx in range(-sw//2, sw//2 + 1):
                x = pos + dx
                if 0 <= x < w:
                    for dy in range(depth):
                        if 0 <= dy < h:
                            result[dy, x] = -2
        elif edge == "bottom":
            for dx in range(-sw//2, sw//2 + 1):
                x = pos + dx
                if 0 <= x < w:
                    for dy in range(depth):
                        y = h - 1 - dy
                        if 0 <= y < h:
                            result[y, x] = -2

    return result


# --- Structural Validation ---

def validate_structure(panels: dict, all_slots: dict) -> list:
    """Check structural integrity and return warnings."""
    warnings = []

    for pid, panel in panels.items():
        w, h = panel["width"], panel["height"]
        if max(w, h) > 50:
            warnings.append(f"Panel '{panel['name']}' is large ({w}x{h}). Consider adding support structures.")
        if len(panel.get("connects_to", [])) < 1 and len(panels) > 1:
            warnings.append(f"Panel '{panel['name']}' has no connections — it won't attach to anything.")
        slots = all_slots.get(pid, [])
        if len(panel.get("connects_to", [])) > 0 and len(slots) == 0:
            warnings.append(f"Panel '{panel['name']}' has connections but no slots.")

    return warnings


# --- Render Panel with Slot Markers ---

def render_panel_with_slots(
    grid: np.ndarray,
    palette: dict,
    panel_name: str,
    cell_size: int = 20,
    ref_interval: int = 10,
) -> Image.Image:
    """Render panel grid with slot positions marked as dashed gray cells."""
    h, w = grid.shape

    # Separate slot markers
    slot_mask = grid == -2
    render_grid = grid.copy()
    render_grid[slot_mask] = -1  # Treat slots as empty for base render

    img = render_pattern(
        render_grid,
        palette["colors"],
        palette["rgb_array"],
        mode="blocks+numbers",
        cell_size=cell_size,
        ref_interval=ref_interval,
        title=panel_name,
    )

    # Overlay slot markers
    draw = ImageDraw.Draw(img)
    margin = cell_size + 4
    title_h = cell_size + 8
    slot_color = (100, 100, 100)

    for y in range(h):
        for x in range(w):
            if slot_mask[y, x]:
                cx = margin + x * cell_size
                cy = margin + title_h + y * cell_size
                # Draw dashed pattern
                draw.rectangle(
                    [cx + 1, cy + 1, cx + cell_size - 2, cy + cell_size - 2],
                    fill=(180, 180, 180),
                    outline=slot_color,
                    width=2,
                )
                # Draw X pattern to indicate slot
                draw.line([(cx + 3, cy + 3), (cx + cell_size - 4, cy + cell_size - 4)],
                          fill=slot_color, width=1)
                draw.line([(cx + cell_size - 4, cy + 3), (cx + 3, cy + cell_size - 4)],
                          fill=slot_color, width=1)

    return img


# --- Assembly Overview ---

def render_assembly_overview(
    plan: dict,
    panel_images: dict,
    panel_stats: list,
    assembly_order: list,
    warnings: list,
) -> Image.Image:
    """Render a single overview image with all panels, assembly order, and stats.

    Layout:
      Title
      [Panel thumbnails in assembly order, with step numbers]
      Assembly instructions text
      Statistics table
      Warnings (if any)
    """
    font_title = get_font(28)
    font_heading = get_font(20)
    font_body = get_font(14)
    font_small = get_font(11)

    # Load panel thumbnails
    thumb_size = 300
    thumbnails = []
    for pid in assembly_order:
        if pid in panel_images:
            try:
                img = Image.open(panel_images[pid])
                img.thumbnail((thumb_size, thumb_size), Image.LANCZOS)
                thumbnails.append((pid, img))
            except Exception:
                thumbnails.append((pid, None))

    # Calculate layout
    cols = min(4, len(thumbnails))
    rows = (len(thumbnails) + cols - 1) // cols
    padding = 20
    thumb_area_w = cols * (thumb_size + padding) + padding
    thumb_area_h = rows * (thumb_size + 50 + padding) + padding  # +50 for label

    # Stats and instructions area
    text_area_h = 300
    warning_area_h = len(warnings) * 25 + 40 if warnings else 0

    total_w = max(thumb_area_w, 800)
    total_h = 80 + thumb_area_h + text_area_h + warning_area_h + padding * 2
    img = Image.new("RGB", (total_w, total_h), (255, 255, 255))
    draw = ImageDraw.Draw(img)

    y_cursor = padding

    # Title
    title_text = f"立体拆件总览: {plan.get('name', '未命名')}"
    draw.text((padding, y_cursor), title_text, fill=(0, 0, 0), font=font_title)
    y_cursor += 45

    total_beads = sum(s["beads"] for s in panel_stats)
    subtitle = f"共 {len(panel_stats)} 个面片 | {total_beads} 颗豆"
    draw.text((padding, y_cursor), subtitle, fill=(100, 100, 100), font=font_body)
    y_cursor += 30

    # Panel thumbnails with step numbers
    for i, (pid, thumb) in enumerate(thumbnails):
        col = i % cols
        row = i // cols
        x = padding + col * (thumb_size + padding)
        y = y_cursor + row * (thumb_size + 50 + padding)

        # Step number circle
        circle_r = 14
        cx, cy = x + circle_r, y + circle_r
        draw.ellipse([cx - circle_r, cy - circle_r, cx + circle_r, cy + circle_r],
                     fill=(50, 120, 200), outline=(30, 80, 160), width=2)
        step_text = str(i + 1)
        bbox = draw.textbbox((0, 0), step_text, font=font_body)
        tw = bbox[2] - bbox[0]
        draw.text((cx - tw // 2, cy - 8), step_text, fill=(255, 255, 255), font=font_body)

        # Panel name
        stat = next((s for s in panel_stats if s["id"] == pid), None)
        label = stat["name"] if stat else pid
        draw.text((x + circle_r * 2 + 5, y + 2), label, fill=(0, 0, 0), font=font_small)

        # Size info
        if stat:
            size_text = f"{stat['size']} ({stat['beads']}颗)"
            draw.text((x + circle_r * 2 + 5, y + 18), size_text, fill=(120, 120, 120), font=font_small)

        # Thumbnail
        if thumb:
            img.paste(thumb, (x, y + 35))
        else:
            draw.rectangle([x, y + 35, x + thumb_size, y + 35 + thumb_size],
                           outline=(200, 200, 200), width=1)
            draw.text((x + 10, y + 35 + thumb_size // 2), f"[{pid}]",
                      fill=(180, 180, 180), font=font_body)

    y_cursor += thumb_area_h + 10

    # Assembly instructions
    draw.line([(padding, y_cursor), (total_w - padding, y_cursor)], fill=(200, 200, 200), width=1)
    y_cursor += 10
    draw.text((padding, y_cursor), "组装顺序", fill=(0, 0, 0), font=font_heading)
    y_cursor += 30

    # Step-by-step text
    panels_by_id = {p["id"]: p for p in plan["panels"]}
    for i, pid in enumerate(assembly_order):
        panel = panels_by_id.get(pid, {})
        name = panel.get("name", pid)
        connects = panel.get("connects_to", [])
        conn_names = [panels_by_id.get(c, {}).get("name", c) for c in connects if c in panels_by_id]

        step_text = f"第{i+1}步: {name}"
        if conn_names and i > 0:
            step_text += f" → 与 {', '.join(conn_names)} 拼接"
        draw.text((padding + 10, y_cursor), step_text, fill=(50, 50, 50), font=font_body)
        y_cursor += 22

    y_cursor += 15

    # Statistics summary
    draw.line([(padding, y_cursor), (total_w - padding, y_cursor)], fill=(200, 200, 200), width=1)
    y_cursor += 10
    draw.text((padding, y_cursor), "用量统计", fill=(0, 0, 0), font=font_heading)
    y_cursor += 30

    for stat in panel_stats:
        text = f"  {stat['name']:12s}  {stat['size']:6s}  {stat['beads']} 颗"
        draw.text((padding, y_cursor), text, fill=(80, 80, 80), font=font_body)
        y_cursor += 20
    draw.text((padding, y_cursor), f"  总计: {total_beads} 颗", fill=(0, 0, 0), font=font_body)
    y_cursor += 25

    # Warnings
    if warnings:
        draw.line([(padding, y_cursor), (total_w - padding, y_cursor)], fill=(200, 200, 200), width=1)
        y_cursor += 10
        draw.text((padding, y_cursor), "警告", fill=(200, 50, 50), font=font_heading)
        y_cursor += 28
        for w in warnings:
            draw.text((padding + 10, y_cursor), f"⚠ {w}", fill=(180, 80, 0), font=font_small)
            y_cursor += 22

    # Crop to actual content height
    img = img.crop((0, 0, total_w, min(y_cursor + padding, total_h)))
    return img


# --- Main ---

def generate_all(
    plan: dict,
    palette: dict,
    output_dir: Path,
    cell_size: int = 20,
    slot_width: int = 1,
    slot_depth_ratio: float = 0.4,
    min_slot_spacing: int = 3,
) -> dict:
    """Generate all panel PNGs from a disassembly plan.

    Returns: manifest dict with files, stats, warnings.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # Index panels by ID
    panels_by_id = {p["id"]: p for p in plan["panels"]}

    # Generate grids and slots for each panel
    all_grids = {}
    all_slots = {}
    files = []

    for panel in plan["panels"]:
        pid = panel["id"]
        grid = generate_panel_grid(panel, palette)
        all_grids[pid] = grid

        slots = design_slots(panel, panels_by_id, slot_width, slot_depth_ratio, min_slot_spacing)
        all_slots[pid] = slots

    # Validate
    warnings = validate_structure(panels_by_id, all_slots)

    # Render each panel
    for panel in plan["panels"]:
        pid = panel["id"]
        grid = all_grids[pid]
        slots = all_slots[pid]

        grid_with_slots = apply_slots_to_grid(grid, slots)
        img = render_panel_with_slots(grid_with_slots, palette, panel["name"], cell_size)

        fname = f"panel_{pid}.png"
        img.save(str(output_dir / fname))
        files.append(fname)

    # Assembly order
    assembly = plan.get("assembly_order", [p["id"] for p in plan["panels"]])

    # Per-panel statistics
    panel_stats = []
    for panel in plan["panels"]:
        pid = panel["id"]
        grid = all_grids[pid]
        total = grid.size
        filled = int(np.sum((grid >= 0)))
        panel_stats.append({
            "id": pid,
            "name": panel["name"],
            "size": f"{panel['width']}x{panel['height']}",
            "beads": filled,
        })

    # Generate assembly overview image
    overview_img = render_assembly_overview(
        plan=plan,
        panel_images={pid: str(output_dir / f"panel_{pid}.png") for pid in all_grids},
        panel_stats=panel_stats,
        assembly_order=assembly,
        warnings=warnings,
    )
    overview_path = output_dir / "assembly_overview.png"
    overview_img.save(str(overview_path))
    files.append("assembly_overview.png")

    manifest = {
        "name": plan.get("name", "unnamed"),
        "output_dir": str(output_dir),
        "files": files,
        "assembly_order": assembly,
        "panel_stats": panel_stats,
        "warnings": warnings,
    }

    # Save manifest
    with open(output_dir / "manifest.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)
    files.append("manifest.json")

    return manifest


# --- CLI ---

def main():
    parser = argparse.ArgumentParser(description="Generate 3D bead panel patterns from disassembly plan")
    parser.add_argument("plan_json", help="Path to disassembly plan JSON")
    parser.add_argument("--palette", default="artkal_s", help="Palette name")
    parser.add_argument("--output-dir", default="./panels_output", help="Output directory")
    parser.add_argument("--cell-size", type=int, default=20, help="Pixels per cell")
    parser.add_argument("--slot-width", type=int, default=1, help="Slot width in beads")
    parser.add_argument("--slot-depth-ratio", type=float, default=0.4, help="Slot depth ratio")
    parser.add_argument("--min-slot-spacing", type=int, default=3, help="Min beads between slots")
    args = parser.parse_args()

    with open(args.plan_json, "r", encoding="utf-8") as f:
        plan = json.load(f)

    palettes_dir = Path(__file__).parent.parent / "data" / "palettes"
    palette = load_palette(args.palette, palettes_dir)

    manifest = generate_all(
        plan=plan,
        palette=palette,
        output_dir=Path(args.output_dir),
        cell_size=args.cell_size,
        slot_width=args.slot_width,
        slot_depth_ratio=args.slot_depth_ratio,
        min_slot_spacing=args.min_slot_spacing,
    )

    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
